name: Test

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1
      env:
        GOROOT: ""
      with:
        args: "run ./..."